# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: http://callfiles.ueibo.com/hexo-theme-laughing/page_background.jpg
page_menu_button: dark
post_background: http://callfiles.ueibo.com/hexo-theme-laughing/post_background.jpg
post_menu_button: light
title_plancehold: 自留地
author:
  head: https://pic4.zhimg.com/9f642001a518694dbb45fbc77a60429b_xl.jpg
  signature: code designer
navication:
  - name: Github
    link: https://github.com/qinyang912
  - name: 知乎
    link: https://www.zhihu.com/people/qin-yang-22
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/qinyang912
  - name: 知乎
    icon: zhihu
    link: https://www.zhihu.com/people/qin-yang-22
# Duoshuo
duoshuo:
  enable: false
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true