# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: /assets/images/page_background.jpg
page_menu_button: dark
post_background: /assets/images/post_background.jpg
post_menu_button: light
title_plancehold: 自留地
author:
  head: /assets/images/zhihu_avatar.jpg
  signature: 自律，才能更自由
navication:
  - name: Github
    link: https://github.com/qinyang912
  - name: RSS
    link: /atom.xml
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/qinyang912
  - name: 知乎
    icon: zhihu
    link: https://www.zhihu.com/people/qin-yang-22
# Duoshuo
duoshuo:
  enable: false
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true

# gitalk
gitalk:
  accessToken: ''
  clientID: '2638ec070f57a82545cc'
  clientSecret: 'b0aeaed2b37065dffdc1ac48133d8a950414e6c4'
  repo: 'nodepie'
  owner: 'qinyang912'
  admin: 'qinyang912'
  